### ISSUE TITLE
FB's fixed-data-table is mispackaged

### ISSUE THREAD

**Issue by sgrove** [cljsjs/packages#137] opened 2015-06-08 20:35 UTC
The source from FDT is somehow mis-compiled/mis-packaged, so that the columns are never actually properly left-offset. Replacing the clojars version with the distributed version from GH seems to fix the issue.

**Comment by martinklepsch** [comment] 2015-06-09 08:52
@ul pinging you as you packaged it and are probably using it (I'm not).

Any ideas what this could be caused by? We earlier had problems with checksums having changed (yeah, wtf) but this doesn't happen in the FDT package.

**Comment by ul** [comment] 2015-06-09 09:11
@sgrove what do you exactly mean by wrong left-offset? In a [demo](https://github.com/ul/fixed-data-table-demo) and my projects table looks like this: ![FDT Demo](http://i.imgur.com/5SSsxqL.png)
I don't see any anomaly.

**Comment by Frozenlock** [comment] 2015-06-14 06:32
@ul would you mind trying with the new 0.3.0?
I get an error whenever I try to click on the scroller.

```js
Uncaught TypeError: undefined is not a function   ------> fixed-data-table.inc.js:4282 
```

**Comment by Frozenlock** [comment] 2015-06-14 06:37
Nevermind, a good ol' lein clean solved the issue.

My apologies.

**Comment by martinklepsch** [comment] 2015-08-30 13:10
Closing this. Please reopen if the issue persists.

**Closed by martinklepsch** 2015-08-30 13:10 UTC
