### ISSUE TITLE
[react-virtualized] Linking issue

### ISSUE THREAD

**Issue by plam3ns** [cljsjs/packages#697] opened 2016-08-19 08:07 UTC
Hello,

I tried to use react-virtualized, but when starting the app - in the browser I get the error "react-virtualized.inc.js:308 Uncaught TypeError: Cannot read property 'shallowCompare' of undefined".

It seems that the function "shallowCompare" is part of the experimental react addons and does not get packaged together with "react-with-addons". As unexperienced with the JS build tools I would appreciate any help to have react-virtualized working.

Regards
Plamen

**Comment by plam3ns** [comment] 2016-10-09 09:22
Hello,

is there a way to contact the author of the cljsjs package for react-virtualized for help to solve the problem? (Ready to pay for the time invested - my contact is plam3ns@gmail.com)

With best regards

**Comment by pesterhazy** [comment] 2017-01-06 15:19
Just ran into this issue as well. Pinging @smitch88 and @ducky427 based off commit history.

**Comment by ducky427** [comment] 2017-01-06 15:50
I managed to get the version working by including `cljsjs/react-with-addons` instead of `cljsjs/react`. So the exact list of dependencies in project.clj was:

```
                [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.229"]
                 [cljsjs/react-with-addons "15.4.0-0"]
                 [cljsjs/react-dom-server "15.4.0-0" :exclusions [cljsjs/react]]
                 [cljsjs/react-dom "15.4.0-0" :exclusions [cljsjs/react]]
                 [reagent "0.6.0" :exclusions [cljsjs/react-dom-server
                                               cljsjs/react-dom]]
                 [cljsjs/react-virtualized "7.11.8-0" :exclusions [cljsjs/react]]]
```

Hope this helps.

**Comment by pesterhazy** [comment] 2017-01-09 13:06
Your example works, thanks @ducky427

**Comment by pesterhazy** [comment] 2017-01-09 13:27
Actually, when creating a FlexTable component, I get this exception:

```
Uncaught TypeError: Cannot read property 'findDOMNode' of undefined
    at FlexTable.value (react-virtualized.inc.js:15849)
    at FlexTable.value (react-virtualized.inc.js:15639)
    at react-dom.inc.js:4704
    at measureLifeCyclePerf (react-dom.inc.js:4514)
    at react-dom.inc.js:4703
    at CallbackQueue.notifyAll (react-dom.inc.js:948)
    at ReactReconcileTransaction.close (react-dom.inc.js:11361)
    at ReactReconcileTransaction.closeAll (react-dom.inc.js:14768)
    at ReactReconcileTransaction.perform (react-dom.inc.js:14715)
    at batchedMountComponentIntoNode (react-dom.inc.js:9742)
```

js/ReactDOM.findDOMNode does exist, so I'm not sure how to fix this.

**Comment by ducky427** [comment] 2017-01-09 13:29
@pesterhazy, it is suggesting that `ReactDOM` package hasn't been loaded. You can explore which libraries are loaded by doing `lein deps :tree`.

**Comment by pesterhazy** [comment] 2017-01-09 13:50
@ducky427 I don't think that's it. I can see window.ReactDOM.findDOMNode from the Chrome console. Also `boot show -d` shows the dependency to be included (cljsjs/react-with-addons "15.4.0-0" and cljsjs/react-dom "15.4.0-0")

**Comment by pesterhazy** [comment] 2017-01-09 13:54
Perhaps related to an issue you opened last summer, https://github.com/bvaughn/react-virtualized/issues/292 ?

**Comment by ducky427** [comment] 2017-01-09 14:05
@pesterhazy, you are right about that. Let me investigate. If it helps, I know that `v7.8.3-1` works.

**Comment by pesterhazy** [comment] 2017-01-09 14:07
Ok so Il looked into it and I can make it work by adding this to a script tag in the head of my html page:

```
<script>
window.ReactDOM = {'findDOMNode': function() {return window.ReactDOM.findDOMNode.apply(this,arguments);}};
</script
```

Of course a terribly ugly hack, but it shows, I think, that this has something to do with evaluation order.

I did try to require cljsjs.react as the first element in the namespace, but that doesn't seem to work.

**Comment by ducky427** [comment] 2017-01-09 14:29
I think the issue is that `react-virtualized.inc.js` is being loaded before `react-dom.inc.js`. This can be verified by looking at `cljs_deps.js` in your cljs->js compiled folder.

**Comment by ducky427** [comment] 2017-01-09 15:01
@pesterhazy, try version `7.11.8-1` of the library. The issue should be fixed.

**Comment by pesterhazy** [comment] 2017-01-15 20:17
@ducky427 I tried the new version and it seems to be working now. I'm just not 100% sure because I can't seem to reproduce the original bug. Thanks!

**Comment by ducky427** [comment] 2017-01-15 20:22
Glad it works now!

**Closed** 2017-01-15 20:22 UTC
Labels: bug
